[workspace]
resolver = "2"
members = [
    "crates/fabric-types",
    "crates/fabric-sim",
    "crates/fabric-topo",
    "crates/fabric-te",
]

[workspace.package]
edition = "2021"
rust-version = "1.78"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
clap = { version = "=4.5.23", features = ["derive"] }
serde = { version = "=1.0.210", features = ["derive"] }
toml = "=0.5.11"
fabric-types = { path = "crates/fabric-types" }
fabric-sim = { path = "crates/fabric-sim" }
fabric-topo = { path = "crates/fabric-topo" }
